services:
  - type: web
    name: cal-web
    plan: free
    repo: https://github.com/bhagirathgudi/docker.git
    dockerfilePath: ./Dockerfile.render
    env: docker
    envVars:

      - key: CALENDSO_ENCRYPTION_KEY
        value: secret

      - key: NEXTAUTH_SECRET
        value: secret

      - key: CRON_API_KEY
        value: 0cc0e6c35519bba620c9360cfe3e68d0

databases:
  - name: cal-postgres
    plan: starter
